# Generated by Django 4.2.5 on 2023-09-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
