# Generated by Django 4.2.5 on 2023-10-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo_app', '0003_rename_user_id_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
