# Generated by Django 4.2.5 on 2023-10-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo_app', '0005_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trick',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
