# Generated by Django 4.2.5 on 2023-10-01 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo_app', '0006_alter_trick_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='trick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='yoyo_app.trick'),
        ),
        migrations.AlterField(
            model_name='trick',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoyo_app.category'),
        ),
    ]
